### ISSUE TITLE
How do I read the excel value instead of formula.

### ISSUE THREAD

**Issue by sunbarve** [felipe-prenholato/openpyxl#16]
I want to read the actual calculated value from .xlsx file but get the formula instead of value.
#For getting value i used.
cell.value

**Comment by merati** [comment]
This will solve your problem.
wb = load_workbook(fname, read_only=True, data_only=True)

**Comment by MrDebashis** [comment]
@merati  This doesnt solve the issue. if data_Only=True, its giving value as None.

**Comment by AbhishekMehar** [comment]
Hi sunbrave,
Did you find any solution? I'm getting same issue.
Please help me to correct it.

**Comment by MrDebashis** [comment]
Openpyxl doesn't support fetching data from a formulated cell. If your
program is going to run in Windows machine or Mac only, then go for
xlwings(Only available for Windows and Mac).

Otherwise you need to do the calculation in your code itself after fetching
raw data from Excel.
