### ISSUE TITLE
"\x0b" character not handled in ws.append()

### ISSUE THREAD

**Issue by Emzilla-01** [felipe-prenholato/openpyxl#23]
Hi there.

```
openpyxl.__version__ == '2.5.9'
```
**In:**
```
from openpyxl import Workbook

wb = Workbook()
ws = wb.active

row = ["test data", "\x0b"]
ws.append(row)
```

**Out:**
```
IllegalCharacterError
```
Alternatively: openpyxl.utils.exceptions.IllegalCharacterError

This case is present on:
- Python 3.6.0 Windows 7 Professional
- Python 3.6.0 Windows Server 2012
- Python 3.6.5 Windows 10 Home

Thanks,
-Em

**Comment by juewuer** [comment]
i just ask a question in stackoverflow, but now i found this issue, it has not been solved now?
https://stackoverflow.com/questions/62906864/illegalcharactererror-occurs-when-i-use-openpyxl-if-the-value-contains-u000b
