### ISSUE TITLE
Saving to io.BytesIO no longer available

### ISSUE THREAD

**Issue by freedaemons** [felipe-prenholato/openpyxl#41]
The functionality to save to a BytesIO object for in-memory handling was removed at some point: I am unable to do
```
working_file = io.BytesIO()
workbook.save(working_file)

wb = load_workbook(filename=working_file)

```

in 3.0.2, but it works fine in 2.6.0

When was this functionality removed? What was the rationale for its removal?

**Comment by adamjsawicki** [comment]
@freedaemons As a heads up, Openpyxl development was moved [here](https://bitbucket.org/openpyxl/openpyxl/src/default/).
