### ISSUE TITLE
openpyxl using too much memory

### ISSUE THREAD

**Issue by Avik1993** [felipe-prenholato/openpyxl#49]
Hi 
I am aware of read_only and write_only mode so wanted suggestions on how to reduce memory footprint for the library.

I have a 30-35 MB file, which I need to read and process and write back the results in same excel.
For doing this task, I cannot use any of read_only or write_only mode; It seems pre 2.4.0 versions had `use_iterators=True` option, to optimize this.

Do you have any suggestion to reduce memory footprint when I need to read+process+write the same file?

**Comment by cryoung6** [comment]
Hi Avik

 

I have actually noticed this same issue and done some research.  The only thing I found was what you mentioned below.  I’m sorry I couldn’t provide a better answer.
