### ISSUE TITLE
Opening and saving this workbook results in corrupt file

### ISSUE THREAD

**Issue by Sandyxuxinxi** [felipe-prenholato/openpyxl#54]
[example.xlsx](https://github.com/chronossc/openpyxl/files/4971575/example.xlsx)

With this code:
```
workbook = openpyxl.load_workbook(workbook_file)
workbook.save(workbook_file.replace('.xlsx', '-test.xlsx'))
```

The resulting file is corrupt. When I click repair, the drawings are lost and all defined names are disabled.

I've found if I edit <definedNames> in workbook.xml and remove all printAreas and printTitles, it will open without showing an error but the drawings are still broken.

**Comment by alsmith** [comment]
I've also had a problem similar to this since ~July, only going back to previous versions of openpyxl doesn't actually solve it either.

I'm only changing one worksheet in my XLS, and that worksheet is actually fine, only out of the other sheets, the others are corrupt after the file is saved.

**Comment by deschman** [comment]
I am experiencing this issue on version 3.0.5. A few sources have mentioned rolling back to 3.0.3 and 3.0.1 but this did not work for me either.

**Comment by alsmith** [comment]
Oops, I actually figured this out in the meantime...

I was reading a workbook, treating it as an io.BytesIO() thingy, modifying it and then just calling the save() method to write back to the same BytesIO buffer. I imagine that seek()ing back to pos 0 before saving, would have also solved this, but also calling save() on a brand new BytesIO fixed it for me.
