### ISSUE TITLE
read_excel() cannot read excel files properly with openpyxl

### ISSUE THREAD

**Issue by oakca** [felipe-prenholato/openpyxl#67]
I opened this issue in `pandas` github, they claim its `openpyxl` issue:

Here is the link: https://github.com/pandas-dev/pandas/issues/40469

`pandas 1.2.3, openpyxl 3.0.7`

I read an excel file with `pandas` via `openpyxl` package. It converts the number in the `'ATC'` column to a weird bitwise string. Previously I was using `xlrd(1.2.0)` instead of `openpyxl` and it was working fine:

```
# with openpyxl 3.0.7
df = pd.read_excel('excel_file.xlsx')

>>>df['ATC']
0    _x0033_40.00
Name: ATC, dtype: object

>>>df['ATC'][0]
'_x0033_40.00'
```

```
# with xlrd 1.2.0
df = pd.read_excel('excel_file.xlsx')

>>>df['ATC']
0    340.0
Name: ATC, dtype: float64

>>>df['ATC'][0]
340.0
```

Here is the excel file if you like to check:
[excel_file.xlsx](https://github.com/pandas-dev/pandas/files/6151138/excel_file.xlsx)

Any work arounds? or I should keep using `xlrd`?

**Comment by nmay231** [comment]
@oakca FYI, this repo is an old clone. Check out https://foss.heptapod.net/openpyxl/openpyxl
